branch-defaults:
  master:
    environment: airapp3-dev
    group_suffix: null
global:
  application_name: airapp3
  branch: null
  default_ec2_keyname: air
  default_platform: Python 3.4
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
